apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: telemetry-agent
  namespace: default
spec:
  owner:
    projectName: default
  componentType:
    kind: ClusterComponentType
    name: deployment/service
  autoDeploy: true
