apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: agent-mcp-chat
  namespace: default
spec:
  owner:
    projectName: default
  componentType:
    kind: ClusterComponentType
    name: deployment/web-application
  autoDeploy: true
